config/routes.rb
Rails.application.routes.draw do

  # ゲストログインルーティング
  devise_scope :customer do
    post 'guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # customer側ルーティング
  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  scope module: :public do
     root 'homes#top'
     get :about, to: 'homes#about'
     resources :events
     resources :posts do
       collection do
         get :popular
       end
       resource :favorites, only: [:create, :destroy]
       resources :post_comments, only: [:create, :destroy]
       resources :recipes, only: [:index, :show, :edit, :update, :create, :destroy] do
       collection do
          get :confirm
        end
      end
     end
    resources :customers, only: [:index, :show, :edit, :update] do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
        get :followings, to: 'customers#followings', as: 'followings'
        get :followers, to: 'customers#followers', as: 'followers'
      end
     resources :categories, only: [:index]
     resources :chats, only: [:show, :create]
     resources :youtube, only: [:index], as: 'youtube'
     resources :notifications, only: [:index] do
       collection do
        delete :destroy_all
      end
     end
   end

  # admin側ルーティング
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
     root 'customers#index'
     resources :customers, only: [:index, :edit, :update, :show] do
      patch :withdraw, to: 'customers#withdraw'
      get :confirm, to: 'customers#confirm'
    end
     resources :posts, only: [:index, :show, :destroy] do
       collection do
         get :analysis, to: 'posts#analysis'
       end
     end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :recipes, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post

  has_many :customer_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :customer_rooms, dependent: :destroy

  has_many :active_notifications, class_name: "Notification", foreign_key: :visiter_id, dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: :visited_id, dependent: :destroy

  has_many :events, dependent: :destroy

  with_options presence: true do
    validates :first_name, length: { maximum: 20 }, format: { with: /\A[一-龥]+\z/ }
    validates :last_name, length: { maximum: 20 }, format: { with: /\A[一-龥]+\z/ }
    validates :first_name_kana, length: { maximum: 20 }, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :last_name_kana, length: { maximum: 20 }, format: { with: /\A[ァ-ヶー－]+\z/ }
    with_options uniqueness: true do
      validates :email
    end
  end

  has_one_attached :customer_image

  def get_customer_image(width, height)
    unless customer_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpeg')
      customer_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    customer_image.variant(resize_to_limit: [width, height]).processed
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def follow(customer)
    relationships.create(followed_id: customer.id)
  end

  def unfollow(customer)
    relationships.find_by(followed_id: customer.id).destroy
  end

  def following?(customer)
    followings.include?(customer)
  end

  #フォロー時の通知
  def create_notification_follow!(current_customer)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ?", current_customer.id, id, 'follow'])
    if temp.blank?
      notification = current_customer.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  def self.guest
  find_or_create_by!(last_name: 'guestuser',  email: 'guest@example.com') do |customer|
    customer.password = SecureRandom.urlsafe_base64
    customer.last_name = "guestuser"
    end
  end

  def full_name
    first_name.to_s + "" + last_name.to_s
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @search = Customer.ransack(params[:q])
    @customers = @search.result
    @customers_all = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

  def confirm
  end

  def withdraw
    @customer = Customer.find(params[:customer_id])
    @customer.update(is_deleted: true)
    redirect_to admin_root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :introduction)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/confirm.html.erb
<div class="container">
  <div class="row-justify-content-center mt-5 pt-5">
    <div class="col-12">
      <h1 class="text-center font-weight-bold">本当に退会させますか？</h1>
    </div>
    <div class="col-12 mt-5 pt-3">
      <h4 class="text-center">退会すると、会員情報登録や<br>
      これまでのデータがなくなってしまいます。<br>
      退会させる場合は、<strong class="text-danger">「退会させる」</strong>をクリックしてください。
      </h4>
    </div>
  </div>
  <div class="text-center">
    <%= link_to "退会しない", root_path, class: "btn btn-sm btn-info" %>
    <%= link_to "退会させる", admin_customer_withdraw_path, method: :patch, data: { confirm: "よろしいですか？" }, class: "btn btn-sm btn-danger" %>
  </div>
  </div>
</div>

app/views/admin/customers/edit.html.erb
<div class="text-center">
  <h1>会員情報編集ページ</h1>
    <%= form_with model: @customer, remote: true do |f| %>
      <div class="field">
        <%= f.label :画像 %><br />
        <%= f.file_field :customer_image, autofocus: true %>
      <div class="field">
        <%= f.label :苗字 %><br />
        <%= f.text_field :first_name, autofocus: true %>
      </div>
      <div class="field">
        <%= f.label :名前 %><br />
        <%= f.text_field :last_name, autofocus: true %>
      </div>
      <div class="field">
        <%= f.label :苗字（カナ） %><br />
        <%= f.text_field :first_name_kana, autofocus: true %>
      </div>
      <div class="field">
        <%= f.label :名前（カナ） %><br />
        <%= f.text_field :last_name_kana, autofocus: true %>
      </div>
      <div class="field">
        <%= f.label :自己紹介 %><br />
        <%= f.text_field :introduction, autofocus: true %>
      </div>
        <%= f.submit "変更", class: 'btn btn-success' %>
      <% end %>
      <%= link_to "退会させますか?", admin_customer_withdraw_path(@customer), method: :patch %>
</div>

app/views/admin/customers/index.html.erb
<div class="text-center">
  <h1 class="w-50 mt-3 pt-3 offset-sm-3"><strong>会員一覧</strong></h1>
     <p>
       <%= search_form_for(@search, url:admin_customers_path) do |f| %>
  		   <%= f.search_field :last_name_cont, placeholder:"キーワードを入力してください", size: "50" %>
  		   <%= f.submit "検索", class: 'btn btn-warning' %>
    	 <% end %>
     </p>
     <div class="container">
       <div class="row">
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>名前</th>
              <th>自己紹介</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <% @customers.each do |customer| %>
          <tbody>
            <tr>
              <td><%= image_tag customer.get_customer_image(200, 200) %></td>
              <td class="align-middle"><%= link_to customer.full_name, admin_customer_path(customer) %></td>
              <td class="align-middle"><%= customer.introduction %></td>
              <% if customer.is_deleted == true %>
                <td class="align-middle">退会済み</td>
              <% else %>
                <td class="align-middle">有効会員</td>
              <% end %>
            </tr>
          </tbody>
          <% end %>
        </table>
       </div>
     </div>
    <div class="mt-4 mb-4 justify-content-center d-flex">
      <%= paginate @customers_all %>
    </div>
</div>

app/views/admin/customers/show.html.erb
<div class="text-center">
  <h1 class="w-50 mt-4 pt-4 offset-sm-3"><strong>会員詳細ページ</strong></h1>
    <div class="row">
        <div class="col-md-3 offset-md-3 mt-5">
          <%= image_tag @customer.get_customer_image(400, 400) %>
        </div>
        <div class="col-md-6 mt-5">
          <table class="table w-50">
            <tbody>
              <tr>
                <th>名前</th>
                <td><%= @customer.first_name + @customer.last_name %></td>
              </tr>
              <tr>
                <th>自己紹介</th>
                <td><%= @customer.introduction %></td>
              </tr>
              <% if @customer.is_deleted == false && @customer.last_name != "guestuser" %>
                <td><%= link_to "退会画面", admin_customer_confirm_path(@customer) %></td>
              <% end %>
              </tr>
            </tbody>
          </table>
        </div>
    </div>
</div>