config/routes.rb
Rails.application.routes.draw do

  # ゲストログインルーティング
  devise_scope :customer do
    post 'guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # customer側ルーティング
  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  scope module: :public do
     root 'homes#top'
     get :about, to: 'homes#about'
     resources :events
     resources :posts do
       collection do
         get :popular
       end
       resource :favorites, only: [:create, :destroy]
       resources :post_comments, only: [:create, :destroy]
       resources :recipes, only: [:index, :show, :edit, :update, :create, :destroy] do
       collection do
          get :confirm
        end
      end
     end
    resources :customers, only: [:index, :show, :edit, :update] do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
        get :followings, to: 'customers#followings', as: 'followings'
        get :followers, to: 'customers#followers', as: 'followers'
      end
     resources :categories, only: [:index]
     resources :chats, only: [:show, :create]
     resources :youtube, only: [:index], as: 'youtube'
     resources :notifications, only: [:index] do
       collection do
        delete :destroy_all
      end
     end
   end

  # admin側ルーティング
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
     root 'customers#index'
     resources :customers, only: [:index, :edit, :update, :show] do
      patch :withdraw, to: 'customers#withdraw'
      get :confirm, to: 'customers#confirm'
    end
     resources :posts, only: [:index, :show, :destroy] do
       collection do
         get :analysis, to: 'posts#analysis'
       end
     end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer
  has_many :post_comments, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_customers, through: :favorites, source: :customer
  has_many :notifications, dependent: :destroy
  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations, dependent: :destroy

  # 今週の投稿数の合計を表示させる
  scope :created_day_ago, -> (number) { where(created_at: number.day.ago.all_day) }
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) } # 今日
  scope :created_yesterday, -> { created_day_ago(1) } # 前日
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..1.week.ago.end_of_day) } # 今週
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) } # 先週

  # 1日毎の投稿数の合計を表示させる
  scope :created_2day_ago, -> { where(created_at: 2.day.ago.all_day) } # 2日前
  scope :created_3day_ago, -> { where(created_at: 3.day.ago.all_day) } # 3日前
  scope :created_4day_ago, -> { where(created_at: 4.day.ago.all_day) } # 4日前
  scope :created_5day_ago, -> { where(created_at: 5.day.ago.all_day) } # 5日前
  scope :created_6day_ago, -> { where(created_at: 6.day.ago.all_day) } # 6日前

  with_options presence: true do
    validates :cook_name
    validates :cooked_day
    with_options length: { maximum: 200 } do
      validates :opinion
    end
  end

  has_one_attached :post_image

  def get_post_image(width, height)
    unless post_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpeg')
      post_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    post_image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end

  # いいね通知
  def create_notification_by(current_customer)
    notification = current_customer.active_notifications.new(
      post_id: id,
      visited_id: customer_id,
      action: "favorite"
    )
    notification.save if notification.valid?
  end

  # コメント通知
  def create_notification_comment!(current_customer, post_comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = PostComment.select(:customer_id).where(post_id: id).where.not(customer_id: current_customer.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_customer, post_comment_id, temp_id['customer_id'])
     end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_customer, post_comment_id, customer_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_customer, post_comment_id, visited_id)
    # コメントは複数回することが考えられるため、1つの投稿に複数回通知する
    notification = current_customer.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: "comment"
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visiter_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @search = Post.ransack(params[:q])
    @posts = @search.result
    @posts_all = Post.page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
  end
  
  def analysis
    @posts = Post.all
    @today_posts = @posts.created_today
    @yesterday_posts = @posts.created_yesterday
    @this_week_posts = @posts.created_this_week
    @last_week_posts = @posts.created_last_week
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/analysis.html.erb
<div class="text-center">
  <h1 class="w-50 mt-3 pt-3 offset-sm-3"><strong>投稿数の前日比・前週比</strong></h1>
    <div class="container">
      <div class="row">
        <div class="col">
          <div class="table_width">
            <table class='table table-bordered'>
              <thead>
                <tr>
                  <th>今日の投稿数</th>
                  <th>前日の投稿数</th>
                  <th>前日比</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><%=  @today_posts.count %></td>
                  <td><%= @yesterday_posts.count %></td>
                  <td>
                    <% if @yesterday_posts.count == 0 %>
                      前日の投稿が0のため計算できません
                    <% else %>
                      <% @the_day_before = @today_posts.count / @yesterday_posts.count.to_f  %>
                      <%= (@the_day_before * 100).round %>%
                    <% end %>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <div class="table_width">
            <table class='table table-bordered'>
              <thead>
                <tr>
                  <th>今週の投稿数</th>
                  <th>前週の投稿数</th>
                  <th>前週比</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><%= @this_week_posts.count %></td>
                  <td><%= @last_week_posts.count %></td>
                  <td>
                    <% if @last_week_posts.count == 0 %>
                      前週の投稿が0のため計算できません
                    <% else %>
                      <% @the_week_before = @this_week_posts.count / @last_week_posts.count.to_f  %>
                      <%= (@the_week_before * 100).round %>%
                    <% end %>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <h4>7日間分の投稿数</h4>
          <table class='table table-bordered'>
            <thead>
              <tr>
                <th>６日前</th>
                <th>５日前</th>
                <th>４日前</th>
                <th>３日前</th>
                <th>２日前</th>
                <th>１日前</th>
                <th>今日</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= @posts.created_day_ago(6).count %></td>
                <td><%= @posts.created_day_ago(5).count %></td>
                <td><%= @posts.created_day_ago(4).count %></td>
                <td><%= @posts.created_day_ago(3).count %></td>
                <td><%= @posts.created_day_ago(2).count %></td>
                <td><%= @posts.created_yesterday.count %></td>
                <td><%= @posts.created_today.count %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    <canvas id="myLineChart"></canvas>
    </div>
</div>
<script>
  $(document).on('turbolinks:load', function() {
    var ctx = document.getElementById("myLineChart");
    var myLineChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
        datasets: [
          {
            label: '投稿数',
            data: [
              <%= @posts.created_day_ago(6).count %>,
              <%= @posts.created_day_ago(5).count %>,
              <%= @posts.created_day_ago(4).count %>,
              <%= @posts.created_day_ago(3).count %>,
              <%= @posts.created_day_ago(2).count %>,
              <%= @posts.created_yesterday.count %>,
              <%= @posts.created_today.count %>
              ],
              borderColor: "rgba(0, 0, 255, 1)",
              backgroundColor: "rgba(0, 0, 0, 0)",
              tension: 0.4
          }
        ],
      },
        options: {
          title: {
            display: true,
            text: '7日間の投稿数の比較'
          },
          responsive: true,
          scales: {
            y: {
              suggestedMin: 0,
              suggestedMax: 10
            },
            x: {
              stacked: true
            },
          },
        }
    });
  });
</script>

app/views/admin/posts/index.html.erb
<div class="text-center">
  <h1 class="w-50 mt-3 pt-3 offset-sm-3"><strong>投稿一覧</strong></h1>
     <p>
       <%= search_form_for(@search, url:admin_posts_path) do |f| %>
 		     <%= f.search_field :cook_name_cont, placeholder: "キーワードを入力してください", size: "50" %>
 		     <%= f.submit "検索", class: 'btn btn-warning' %>
	     <% end %>
     </p>
     <div class="container">
       <div class="row">
         <div class="col">
          <table class="table">
            <tbody>
              <% @posts.each do |post| %>
                <tr>
                  <th class="align-middle">料理名</th>
                  <td class="align-middle"><%= link_to post.cook_name, admin_post_path(post) %></td>
                  <td><%= image_tag post.get_post_image(200, 200) %></td>
                </tr>
                <tr>
                  <th>作った日</th>
                  <td class="align-middle"><%= post.cooked_day.strftime('%Y/%m/%d') %></td>
                </tr>
                <tr>
                  <th>感想</th>
                  <td><%= post.opinion %></td>
                </tr>
                <% if post.customer == current_customer %>
                  <%= link_to "編集", edit_post_path(post), class: 'btn btn-success' %>
                <% end %>
              <% end %>
            </tbody>
          </table>

         </div>
       </div>
     </div>
  <div class="mt-4 mb-4 justify-content-center d-flex">
    <%= paginate @posts_all %>
</div>

app/views/admin/posts/show.html.erb
<div class="text-center">
  <h1 class="w-50 mt-3 pt-3 offset-sm-3"><strong><%= @post.cook_name %></strong></h1>
</div>
  <div class="container">
    <div class="row mt-5">
      <div class="col-lg-5 offset-md-1">
        <table class="table w-100">
          <tbody>
            <tr>
              <th>感想</th>
              <td><%= @post.opinion %></td>
            </tr>
              <% if @post.customer == current_customer %>
              <div class="row justify-content-center">
                <div class="btn-group">
                  <tr>
                    <%= link_to "編集", edit_post_path(@post), class: 'btn btn-success' %>
                    <%= link_to "削除", post_path(@post), method: :delete, remote: true, class: 'btn btn-danger' %>
                  </tr>
                </div>
              </div>
              <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-lg-5 offset-md-1">
        <%= image_tag @post.get_post_image(400, 400) %>
      </div>
      </div>
    </div>
  </div>