config/routes.rb
Rails.application.routes.draw do

  # ゲストログインルーティング
  devise_scope :customer do
    post 'guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # customer側ルーティング
  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  scope module: :public do
     root 'homes#top'
     get :about, to: 'homes#about'
     resources :events
     resources :posts do
       collection do
         get :popular
       end
       resource :favorites, only: [:create, :destroy]
       resources :post_comments, only: [:create, :destroy]
       resources :recipes, only: [:index, :show, :edit, :update, :create, :destroy] do
       collection do
          get :confirm
        end
      end
     end
    resources :customers, only: [:index, :show, :edit, :update] do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
        get :followings, to: 'customers#followings', as: 'followings'
        get :followers, to: 'customers#followers', as: 'followers'
      end
     resources :categories, only: [:index]
     resources :chats, only: [:show, :create]
     resources :youtube, only: [:index], as: 'youtube'
     resources :notifications, only: [:index] do
       collection do
        delete :destroy_all
      end
     end
   end

  # admin側ルーティング
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
     root 'customers#index'
     resources :customers, only: [:index, :edit, :update, :show] do
      patch :withdraw, to: 'customers#withdraw'
      get :confirm, to: 'customers#confirm'
    end
     resources :posts, only: [:index, :show, :destroy] do
       collection do
         get :analysis, to: 'posts#analysis'
       end
     end
  end
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h4><%= pluralize(obj.errors.count, "エラー") %> が発生しています</h4>
      <% obj.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<div class="notifications">
  <% flash.each do |key, value| %>
   <h4 class="text-center" style="background-color: #F0F8FF;">️<%= content_tag(:div, value, class: key) %></h4>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="border" id="copyright">
  <p class="font-weight-bold">Copyright © 2022*  github.com/suzu784/menu_app</p>
</div>

app/views/layouts/_header.html.erb
<nav class="border border-dark navbar p-5 bg-transparent navbar-light", style="background:rgba(255,255,255,1);" id="navi">
  <%= link_to "/" do %>
    <h2 class="text text-dark ", style="font-family: Hannotate SC;"><i class="fas fa-calendar"></i>献立シェアアプリ</h2>
  <% end %>
<div id="sp-menu">
  <h2>MENU</h2>
  <div class="row">
    <div class="col-md-6 d-none d-xl-block">
      <%= image_tag 'logo.png' %>
    </div>
    <div class="col-md-6">
      <ul>
        <!--会員ログイン時-->
          <% if customer_signed_in? %>
            <li><%= link_to about_path do %>
              <i class="fas fa-calendar"></i>献立シェアアプリについて
            <% end %>
            </li>
            <% if unchecked_notifications.any? %>
              <i class="fa fa-circle" style="color: gold;"></i>
            <% end %>
            <li><%= link_to events_path do %>
              <i class="fas fa-home"></i>マイページ
            <% end %>
            </li>
            <li><%= link_to new_post_path do %>
              <i class="fas fa-edit"></i>新規投稿
            <% end %>
            </li>
            <li><%= link_to posts_path do %>
              <i class="fas fa-book-open"></i>投稿一覧
            <% end %>
            </li>
            <li><%= link_to popular_posts_path do %>
              <i class="fas fa-crown"></i>人気投稿
            <% end %>
            </li>
            <li><%= link_to youtube_index_path do %>
              <i class="fas fa-video"></i>レシピ検索
            <% end %>
            </li>
            <li><%= link_to customers_path do %>
              <i class="fas fa-user"></i>会員一覧
            <% end %>
            </li>
            <li><%= link_to notifications_path do %>
              <i class="fas fa-bell"></i>通知一覧
            <% end %>
            </li>
            <li><%= link_to destroy_customer_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt"></i>ログアウト
            <% end %>
            </li>
          <!--管理者ログイン時-->
          <% elsif admin_signed_in? %>
            <li><%= link_to analysis_admin_posts_path do %>
              <i class="fas fa-chart-line"></i>分析機能
            <% end %>
            </li>
            <li><%= link_to admin_customers_path do %>
              <i class="fas fa-user"></i>会員一覧
            <% end %>
            </li>
            <li><%= link_to admin_posts_path do %>
              <i class="fas fa-book-open"></i>投稿一覧
            <% end %>
            </li>
            <li><%= link_to destroy_admin_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt"></i>ログアウト
            <% end %>
            </li>
          <!--非ログイン時-->
          <% else %>
            <li><%= link_to root_path do %>
              <i class="fas fa-desktop"></i>トップメニュー
            <% end %>
            </li>
            <li><%= link_to about_path do %>
              <i class="fas fa-calendar"></i>献立シェアアプリについて
            <% end %>
            </li>
            <li><%= link_to new_customer_registration_path do %>
              <i class="fas fa-user"></i>新規登録
            <% end %>
            </li>
            <li><%= link_to new_customer_session_path do %>
              <i class="fas fa-sign-in-alt"></i>ログイン
            <% end %>
            </li>
          <% end %>
      </ul>
    </div>
  </div>
</div>

<div id="hm-icon">
  <a class="menu-trigger">
    <span></span>
    <span></span>
    <span></span>
  </a>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>献立シェアアプリ</title>
    <%= favicon_link_tag('logo.png') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <header id="header">
        <%= render 'layouts/header' %>
      </header>
      <main>
       <div id="flash-message"><%= render 'layouts/flash' %></div>
      </main>
      <%= yield %>
    </div>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>